### PR TITLE
Add typescript types

### PR DESCRIPTION
**Pull request by retupmoca**
This PR attempts to add Typescript types for #23 while making the minimum changes to the project. Most of these types I wrote before realizing there was an issue in progress, although I did pull a couple of pieces from the issue that were done better than mine.

I'm not very familiar with rollup, but a local build seemed to work correctly.

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Thanks for this I will take a look at the weekend, one thing that might need adding, is the types of the properties of the html iframe element, as they can also be passed via this React element

**Comment by retupmoca** [comment]
I believe the iframe element types should be already included via the `type IframeProps` - that uses the same types for a basic <iframe> that React itself does

**Comment by davidjbradshaw** [comment]
Oh cool that makes it easy

**Comment by davidjbradshaw** [comment]
Thanks, released as v1.0.4

**Comment by Slion** [comment]
Sadly this seems to be react specific right?

**Pull request merged**
