### PR TITLE
check if iframeRef.current exists on close

### LINKED ISSUE #8: Error when iframe closes
Hi,
Relating to this issue: https://github.com/davidjbradshaw/iframe-resizer-react/issues/4
The error is still occurring in v1.0.1 and it's quite annoying during development time.
image

This is because it still tries to get 'Id' from 'iframeRef.current' regardless if its null or not for the string interpolation.
Thanks.

### PR DESCRIPTION
**Pull request by calvinmetcalf**
fixes #8

### CODE REVIEW

**Comment by Meberem** [comment]
@davidjbradshaw would you be able to review this fix? I would really appreciate being able to use this in my project

**Comment by Gfast2** [comment]
Awesome, May I ask in which (up-comming) Version is this PR included? Thanks & have a nice day!

**Comment by davidjbradshaw** [comment]
Just trying to make a release atm, but my work machine is not playing ball.
Will give it one more try and if not I will push out a release over the
weekend.

Sorry for the delay, it's been a busy week.

**Comment by Gfast2** [comment]
@davidjbradshaw,

Thank you for your effort again!

**Comment by davidjbradshaw** [comment]
Released as v1.0.2

**Comment by Gfast2** [comment]
Tested, like a charm! Have a nice weekend!

**Pull request merged**
