### PR TITLE
fix type for typescript

### PR DESCRIPTION
**Pull request by gespispace**
Property `src` is required

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Just wondering why you added `style` as well? 

There is a total of 50 different props that can be passed via this component and I don't think it makes a lot of sense to add them all as propTypes. Maybe extending https://www.npmjs.com/package/@types/iframe-resizer would make more sense?

**Comment by gespispace** [comment]
Yes, maybe `@types/iframe-resizer-react` help but this package is not. Can you created this package?

**Comment by gespispace** [comment]
I just used two property in IframeRisizer `src` and `style`.

**Comment by davidjbradshaw** [comment]
> Yes, maybe `@types/iframe-resizer-react` help but this package is not. Can you created this package?

I am not a type script user, please feel free to create that or make a full typings PR.

**Comment by gespispace** [comment]
I will not create pr. you can close pr.

**Pull request closed without merging**
